chore: enhance app change process documentation
eclipse-tractusx/portal-assets pull request #110
Opened 2023-08-01 15:16 UTC by jjeroch

## Description

Added end user and developer docu for app change process

## Why

Implemented recently
- App Image Change
- App Description Change
- App Deactivation
- App Instance URL

## Issue

n/a

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-02 10:22 UTC, Phil91 requested changes

2023-08-02 10:22 UTC, Phil91 commented on developer/04. Apps/06. App Change Process/01. Summary.md
> +
The file is currently empty, is that wanted?

2023-08-03 10:49 UTC, oyo approved these changes

2023-08-07 06:09 UTC, Phil91 approved these changes

2023-08-07 06:11 UTC, merged