docs: update release process
eclipse-tractusx/portal-assets pull request #132
Opened 2023-08-17 08:54 UTC by evegufy

## Description

update release process

## Why

there were a couple of change to the release process in the last months.

## Issue

n/a

## Checklist

- [x] I have performed a self-review of my own code

2023-08-17 09:13 UTC, Phil91 requested changes
Not sure where to place it and if it makes sense to include it in here, but when merging the rcX branch all existing PRs with the RC branch as the target should've been changed already. Otherwise github will automatically close the PRs because the rc branch will be deleted when merging

2023-08-17 09:13 UTC, Phil91 commented on developer/Technical Documentation/Operations/Release-Process.md
>  * Bug Fixes
Could we add Known Knowns as well?

2023-08-17 09:13 UTC, Phil91 commented on developer/Technical Documentation/Operations/Release-Process.md
> +Once a version has been released, migrations **mustn't be aggregated** in order to ensure upgradeability this also applies to **release candidates ) RC1 and hotfixes**.
is the ) wanted?

2023-08-17 09:29 UTC, evegufy commented on developer/Technical Documentation/Operations/Release-Process.md
> +Once a version has been released, migrations **mustn't be aggregated** in order to ensure upgradeability this also applies to **release candidates ) RC1 and hotfixes**.
no, too much search & replace ;) thanks!

2023-08-17 09:29 UTC, evegufy commented on developer/Technical Documentation/Operations/Release-Process.md
>  * Bug Fixes
done

2023-08-17 09:53 UTC, evegufy commented
> Not sure where to place it and if it makes sense to include it in here, but when merging the rcX branch all existing PRs with the RC branch as the target should've been changed already. Otherwise github will automatically close the PRs because the rc branch will be deleted when merging

added to 'RC: provide successive RC branch' step

2023-08-18 04:40 UTC, oyo approved these changes

2023-08-18 07:43 UTC, Phil91 approved these changes

2023-08-18 13:38 UTC, merged