updates(company roles): Fix typo
eclipse-tractusx/portal-assets pull request #150
Opened 2023-08-28 14:18 UTC by manojava-gk

## Description

addressed all the feedback on text frame, typo from testers

## Why

feedback from tester

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-08-29 14:30 UTC, oyo submitted a review, later dismissed
please remove absolute links to demo.catena-x.net

2023-08-29 14:30 UTC, oyo commented on public/assets/content/de/companyroles.json
> +                  "id": "https://portal.int.demo.catena-x.net/documentation/?path=docs%2F06.+Certificates%2F01.+UseCase+Participation.md",
Absolute URLs to Catena-X environments are not allowed

2023-09-06 08:39 UTC, evegufy requested changes

2023-09-08 06:29 UTC, evegufy approved these changes

2023-09-08 06:30 UTC, merged