updates(static templates): update guidelines
eclipse-tractusx/portal-assets pull request #170
Opened 2023-10-10 10:02 UTC by manojava-gk

## Description

update static template guidelines. move images to a new directory

## Why

add new templates

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-10-10 10:18 UTC, manojava-gk commented
> @manojava-gk thanks! with my comment [here](https://github.com/eclipse-tractusx/portal-assets/pull/169#pullrequestreview-1666947312) I meant to establish the static folder under the docs folder on root level so [/docs](https://github.com/eclipse-tractusx/portal-assets/tree/main/docs). Could please adjust the PR accordingly?
> 
> Out of curiosity, why did close the PR #169 and open this new one?

The moment someone commits in the upstream, my local struggles to sync(no push no pull). I'm not sure about the reason though, I keep on create new PRs whenever there is a commit available in the upstream.

2023-10-10 11:12 UTC, evegufy approved these changes

2023-10-11 07:18 UTC, jjeroch commented
@manojava-gk  can we get a bit more specific in the section "#### New Page creation" I wonder if a new developer would now really know what to do. Does it maybe make sense to refer to folders or files where changes need to get applied? What do you think?

2023-10-11 07:18 UTC, jjeroch requested changes
Looks good

2023-10-11 07:28 UTC, merged