chore: adjust technical user role documentation
eclipse-tractusx/portal-assets pull request #171
Opened 2023-10-10 13:56 UTC by Phil91

## Description

Adjust technical user roles to the new roles

## Why

To have the latest roles documented

## Issue

N/A - Jira Issue: CPLP-3312

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code

2023-10-11 20:18 UTC, jjeroch requested changes

2023-10-11 20:18 UTC, jjeroch commented on developer/Technical Documentation/Identity & Access/05. Roles & Rights Concept.md
> +<img width="1386" alt="image" src="https://github.com/catenax-ng/tx-portal-assets/assets/7672600/ab00ce40-90e5-408e-a4c8-c0b5b81f7955">
@Phil91 kannst du das Bild nochmal neu ziehen - mir war heute aufgefallen das in der Tabelle noch die "Registration External" Rolle gefällt hatte. Habs heute in Confluence nachgezogen.

2023-10-11 20:18 UTC, jjeroch commented on docs/03. User Management/03. Technical User/02. Create Technical User.md
> +* Identity Wallet Management (technical user to view and modify own company wallet)
@Phil91 mir fällt gerade auf, dass wir hier noch genauer werden können => "technical user to access own company wallet - request VC, request VP, store VC, etc."

2023-10-12 17:56 UTC, Phil91 commented on developer/Technical Documentation/Identity & Access/05. Roles & Rights Concept.md
> +<img width="1386" alt="image" src="https://github.com/catenax-ng/tx-portal-assets/assets/7672600/ab00ce40-90e5-408e-a4c8-c0b5b81f7955">
adjusted

2023-10-24 07:59 UTC, jjeroch requested changes
<img width="96" alt="image" src="https://github.com/eclipse-tractusx/portal-assets/assets/94133633/50b2b696-5862-43d0-a521-586a6ac45240">
kannst du den noch umbenennen

2023-10-24 08:20 UTC, Phil91 commented
> <img alt="image" width="96" src="https://user-images.githubusercontent.com/94133633/277588512-50b2b696-5862-43d0-a521-586a6ac45240.png"> kannst du den noch umbenennen

adjusted

2023-10-24 13:09 UTC, jjeroch approved these changes

2023-11-02 11:14 UTC, jjeroch approved these changes

2023-11-02 12:30 UTC, oyo approved these changes

2023-11-02 12:32 UTC, merged