change/upgrade portal db changes
eclipse-tractusx/portal-assets pull request #172
Opened 2023-10-11 06:29 UTC by jjeroch

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-11 06:29 UTC, jjeroch commented
@Phil91 kannst du die Doku bitte übernehmen - die Teile die ich bereits gestartet habe hab ich einfach mal reingepackt - gerne ändern ;)

2023-10-20 06:30 UTC, Phil91 commented
@jjeroch i've added a few things to the documenation and added @evegufy to review it

2023-11-13 11:59 UTC, evegufy requested changes

2023-11-13 11:59 UTC, evegufy commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +<img width="779" alt="image" src="https://github.com/catenax-ng/tx-portal-assets/assets/94133633/57447ebf-1d56-48e4-a3ee-d8a017a2e605">
@Phil91 Could be please add all the images in this file add or move to docs/static and reference them accordingly?

2023-11-13 12:46 UTC, evegufy approved these changes

2023-11-13 12:53 UTC, merged