feat(icon): added process icon
eclipse-tractusx/portal-assets pull request #176
Opened 2023-10-19 09:08 UTC by nidhigarg-bmw

## Description

Add Process icon

## Why

To use this icon in frontend repo

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-10-20 13:06 UTC, oyo requested changes
this is just a png embedded in an svg - in this case we have no benefit from svg and it's better to use the png directly. It's not that difficult to create a nice svg from scratch. 

Also license file is missing - check other images who have such a file associated with them

2023-10-24 08:26 UTC, oyo commented
@nidhigarg-bmw are you adding a license file here? then we can merge that

2023-10-24 08:39 UTC, nidhigarg-bmw commented
> @nidhigarg-bmw are you adding a license file here? then we can merge that

@oyo Just added you can review now.

2023-10-24 11:07 UTC, oyo approved these changes

2023-10-24 11:07 UTC, merged