updates(osp and conformity): new content
eclipse-tractusx/portal-assets pull request #201
Opened 2023-11-21 10:43 UTC by manojava-gk

## Description

osp page content updates.
conformity page content updates

## Why

change request

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-12-01 07:20 UTC, jjeroch commented on developer/Technical Documentation/Identity & Access/11. Upgrade Details.md
> +## Upgrade Details
@manojava-gk  you have added this section?

2023-12-01 07:21 UTC, jjeroch commented on public/assets/content/de/companyroles.json
>    "confirmity": {
spelling mistake - not "confirmity" it must be "conformity"

2023-12-01 07:52 UTC, manojava-gk commented on public/assets/content/de/companyroles.json
>    "confirmity": {
updated this typo in all the places

2023-12-05 06:44 UTC, jjeroch commented on developer/Technical Documentation/Identity & Access/11. Upgrade Details.md
> +## Upgrade Details
@evegufy can you please have a look at this. From my point of view this should not happen. Please suggest how this can get avoided or even fixed now.

2023-12-05 07:28 UTC, evegufy commented on public/assets/content/en/companyroles.json
> +              "id": " https://portal.int.demo.catena-x.net/idpmanagement ",
Our environments are not be referenced within our repositories, please change.

2023-12-05 07:33 UTC, evegufy requested changes
@manojava-gk  IMO you merged some obsolete state of main into your feature branch. Please rebase and drop all irrelevant commits and contact me if you need help for this.
Generally, merging main into you feature isn't a good approach, I recommend checking out directly from main in the future.

cc: @jjeroch

2023-12-05 07:33 UTC, evegufy commented on public/assets/content/en/companyroles.json
> +              "id": "https://portal.int.demo.catena-x.net/technicaluser",
Our environments are not be referenced within our repositories, please change.

2023-12-05 08:46 UTC, manojava-gk commented
@jjeroch FYI issue got resolved.
Thanks @evegufy

2023-12-05 08:51 UTC, evegufy requested changes
Please update PR title to [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/)

2023-12-05 09:11 UTC, jjeroch approved these changes

2023-12-05 09:30 UTC, evegufy commented
@manojava-gk 'updates' isn't a conventional commits type:
![image](https://github.com/eclipse-tractusx/portal-assets/assets/46191613/b20da1db-a464-4414-b7bf-a7382430653e)
Please have a look at the examples:
![image](https://github.com/eclipse-tractusx/portal-assets/assets/46191613/274c73f2-dc9e-4183-b233-77a3e31e9121)

2023-12-05 17:26 UTC, evegufy approved these changes

2023-12-05 17:26 UTC, merged