Patch 1
eclipse-tractusx/portal-assets pull request #209
Opened 2023-11-27 13:41 UTC by SSIRKC

## Description

As stated during the security assessment the security team is currently moving all Confluence assessment to GitHub.
This assessment includes the documented and agreed version for the portal application and the in scope components.

## Why

The pull adds the assessment to the already existing data flow diagram. The diagram itself has not been changed.

## Issue

None

## Checklist

Please delete options that are not relevant.

- [ x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ x] I have created and linked IP issues or requested their creation by a committer
- [ x] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x ] I have performed a self-review of my own code
- [x ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ x] I have checked that new and existing tests pass locally with my changes
- [ x] I have commented my code, particularly in hard-to-understand areas

2023-11-29 07:20 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +
Could you please also portal-iam https://github.com/eclipse-tractusx/portal-iam?

2023-11-29 07:25 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        subgraph Company realms
Could you please add multiple company realms under sharedidp? Like here https://github.com/SSIRKC/portal-assets/blob/patch-1/developer/Technical%20Documentation/Architecture/Data-Flow.md?plain=1#L54. I'd say at least two, to make clear that there are multiple company realms available in the sharedidp.

2023-11-29 07:32 UTC, evegufy requested changes
@SSIRKC Thank you for the PR?

Could you please rebase to the release/v1.7.0 branch? I think you checkout out from the main branch.

Could you please have a more detailed look at the linkages? I think in the version hosted in Confluence we had a lot of dotted links, should that be the case in this diagram as well?

Could you please also add information which other security checks are in place besides the thread modelling? Like the other ones mentioned here https://github.com/eclipse-tractusx/sig-release/issues/107.

2023-11-29 08:35 UTC, SSIRKC commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +
Done :)

2023-11-29 08:40 UTC, SSIRKC commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        subgraph Company realms
Hi Evelyn, did I get you right to use the provided diagram? I switched it to the one you provided now.

2023-11-29 09:51 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        subgraph Company realms
Hi @SSIRKC , yes using the other diagram is good. That should be the starting point for the following:
> Could you please have a more detailed look at the linkages? I think in the version hosted in Confluence we had a lot of dotted links, should that be the case in this diagram as well?

2023-11-29 09:53 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        subgraph Company realms
You could also remove the separate file for the [Data Flow diagram](https://github.com/SSIRKC/portal-assets/blob/patch-1/developer/Technical%20Documentation/Architecture/Data-Flow.md), if it's now completely integrated in the Security Assessment file.

2023-11-29 12:33 UTC, evegufy commented
> > @SSIRKC Thank you for the PR?
> > Could you please rebase to the release/v1.7.0 branch? I think you checkout out from the main branch.
> > Could you please have a more detailed look at the linkages? I think in the version hosted in Confluence we had a lot of dotted links, should that be the case in this diagram as well?
> > Could you please also add information which other security checks are in place besides the thread modelling? Like the other ones mentioned here [eclipse-tractusx/sig-release#107](https://github.com/eclipse-tractusx/sig-release/issues/107).
> 
> Hi @evegufy,
> 
> I will correct the branch. For me it looks like branch release/v1.7.0. Have to figure out what happend here.
> 

I don't think the rebase worked. I still the 12 commits added. Could you please check again?

> In Confluence were dotted lines, however, they only serve a visual purpose. I can do this here as well if you like.
> 

Would be great if you could transfer the dotted lines, this might improve the readability of the mermaid diagram, which currently isn't that great.

> The security checks that you normally mention in an assessment are meant to respond to findings within the thread modelling process. I would rather not add SCA/SAST or DAST scan results here, but if you like we could meet up and prepare a list of general controls that we can list here. There are best practices that you can sign off e.g. input validation, encryption of data at rest/transfer/use, etc. Should we do that?

I don't mean to add the scan results, just mentioning which checks we're doing, which purpose they serve and which criteria are we following (for instance no critical or high findings).

2023-12-01 13:33 UTC, SSIRKC commented
Added dotted lines and bold lines for better visualization. Also added an overview/legend of symbol meanings. I will also add the security controls.

2023-12-04 09:12 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        C1 <-.-> D1
Please also add description of this link like done for <--> and https connections.

2023-12-04 09:12 UTC, evegufy commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        C1 <==> D1
Please also add description of this link like done for <--> and https connections.

2023-12-05 07:59 UTC, evegufy commented
@SSIRKC could you please give me an estimate until when you'll be able to add the last changes? I need to close the v1.7.0 latest by tomorrow.

2023-12-05 11:24 UTC, SSIRKC commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        C1 <-.-> D1
Done :)

2023-12-05 11:24 UTC, SSIRKC commented on developer/Technical Documentation/Architecture/Security-Assessment.md
> +        C1 <==> D1
Done :)

2023-12-05 17:01 UTC, evegufy approved these changes
@SSIRKC Thanks you! Looks good.
I just did some small changes still.

2023-12-05 17:02 UTC, merged