Chore: remove picture references to catenax-ng
eclipse-tractusx/portal-assets pull request #243
Opened 2024-02-02 14:34 UTC by johanneskueffner

## Description
- add pictures to docs static
- link pictures from doc static

## Why
Cleanup

## Issue
[Link to Github issue.](https://github.com/eclipse-tractusx/portal-assets/issues/241)

## Checklist
- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x] I have performed a self-review of my own changes

2024-02-02 15:08 UTC, evegufy requested changes
Looks good so far!
Just have a look at my comment 

And please also add the following as the [issue](https://github.com/eclipse-tractusx/portal-assets/issues/241) requests:
"Please also enhance the 'How to contribute' guide with a description about how to manage images (upload to static/docs, create license file, link in the documentation...)."

And correct the PR title, I think you wanted to write user-images instead of catenax-ng.

2024-02-11 19:12 UTC, jjeroch commented
Hi, before merging we need to validate what we merge first - in parallel following prs got created and might impact this pr

- https://github.com/eclipse-tractusx/portal-assets/pull/245
- https://github.com/eclipse-tractusx/portal-assets/pull/246
- https://github.com/eclipse-tractusx/portal-assets/pull/244

2024-02-12 12:33 UTC, evegufy requested changes
could you please adjust the cases of user-images in the following files:
https://github.com/catenax-ng/tx-portal-assets/blob/chore/remove-user-images/docs/developer/01.%20Onboarding/03.%20Registration%20Approval/03.%20Registration%20Approval%20Process.md
https://github.com/catenax-ng/tx-portal-assets/blob/chore/remove-user-images/docs/user/01.%20Onboarding/03.%20Registration%20Approval/03.%20Registration%20Approval%20Process.md

2024-02-12 13:55 UTC, evegufy approved these changes

2024-02-12 14:26 UTC, jjeroch approved these changes

2024-02-12 15:07 UTC, merged