Updates/doc osp partner perspective
eclipse-tractusx/portal-assets pull request #265
Opened 2024-02-27 08:41 UTC by Leon-Gr

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have added copyright and license headers, footers (for .md files) or files (for images)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-28 14:36 UTC, evegufy reviewed
looks good in general but the file is currently located directly under docs/user/01. Onboarding, is that supposed to the location?

2024-02-28 15:28 UTC, jjeroch requested changes

2024-02-28 15:28 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +This part of the documentation will help users, who were registered via an Onboarding Service Provider (OSP) to get along. Please note, that this documentation only starts at the time you were succes
@evegufy  can you quickly check if that will actually work? Linking to a developer doc docu. Will this successfully work in our help app? 
@Leon-Gr  I think we should add a own OSP Persona inside the user documentation describing the OSP from a pure functional side

2024-02-28 15:28 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +As soon as the registration process is done on your OSP side, you will receive a welcome mail, that contains information on how you can proceed. It will provide you with a link and information about
I suggest to include additional information (as we have it inside the email) that due to the OSP link the login is supposed to take place via the email mentioned login account and with the personal user credentials which the user does know already from the OSP network login

2024-02-28 15:28 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +When you first log in, you will be prompted with an overlay that asks you to consent to the terms and conditions. As soon as this is done the overlay will close and you can start browsing the site.
We should mention that the the terms and conditions may vary based on the company assigned role (given by the OSP registration creation).

2024-02-28 15:28 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +### Welcome Mail & First Login
I miss anything about declining my registration - isnt that supported yet?

2024-02-28 15:28 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +You will then see an overlay that tells you about the status of your registration. The individual steps, that need to be checked and done prior to your final registration will be listed here. You can
Missing: as soon as all steps are successfully performed; an automatic email will get send out

2024-02-28 15:37 UTC, evegufy commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +This part of the documentation will help users, who were registered via an Onboarding Service Provider (OSP) to get along. Please note, that this documentation only starts at the time you were succes
@jjeroch just checked the link for Audit Log Details in [here](https://raw.githubusercontent.com/eclipse-tractusx/portal-assets/main/docs/user/03.%20User%20Management/02.%20Modify%20User%20Account/06.%20Delete%20User.md) on INT, it works

2024-02-29 08:04 UTC, jjeroch commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +### Welcome Mail & First Login
danke @Leon-Gr

2024-02-29 08:08 UTC, Leon-Gr commented on docs/user/01. Onboarding/OSPDrivenOnboarding.md
> +In case you received the earlier mentioned welcome mail and you do not want to part of the dataspace, you can scroll down to the bottom of the page and click the link for declining the registration.
Done

2024-02-29 10:02 UTC, jjeroch approved these changes

2024-02-29 17:17 UTC, evegufy requested changes
looks good so far, just one additional note and please also update the index.md

2024-02-29 17:17 UTC, evegufy commented on docs/user/01. Onboarding/04. OSP/01. Oboarding with an OSP.md
> +As soon as the registration process is done on your OSP side, you will receive a welcome mail, that contains information on how you can proceed. It will provide you with a link and information about
please remove reference to int env

2024-03-05 14:40 UTC, evegufy approved these changes

2024-03-05 14:41 UTC, merged