feat(upgrade):  changes in version upgrade doc for company certificates
eclipse-tractusx/portal-assets pull request #267
Opened 2024-02-28 08:15 UTC by AnuragNagpure

…ates db

document for release 1.8.0 the change made in version upgrade doc for developer

 company certificates - https://github.com/eclipse-tractusx/sig-release/issues/326

Please include a summary of the change.

new feature database tables for company certificate reference added.

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

#264 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-28 08:18 UTC, Phil91 requested changes

2024-02-28 08:18 UTC, Phil91 commented on docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +COMPANY-CERTIFICATE{
There seems to be an issue with the mermaid diagram. Please have a look at Prasanas PR #266 as an example

2024-02-28 11:03 UTC, AnuragNagpure commented on docs/developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +COMPANY-CERTIFICATE{
Updation done in mermaid diagram.

2024-02-29 12:43 UTC, evegufy approved these changes

2024-03-01 09:38 UTC, merged