Docs adding new get document certificate endpoints
eclipse-tractusx/portal-assets pull request #297
Opened 2024-03-31 19:16 UTC by jjeroch

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have added copyright and license headers, footers (for .md files) or files (for images)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-04-04 05:45 UTC, oyo requested changes
A tiny typo

2024-04-04 05:45 UTC, oyo commented on docs/developer/08. Certificate Management/03. Certificate Publishing.md
> +The `GEt /api/administration/companydata/companyCertificates/{documentId}` endpoint is used to to fetch the certificate document of your own company from the backend. This endpoint is specifically de
GEt -> GET

2024-04-22 11:21 UTC, oyo approved these changes

2024-05-15 13:36 UTC, evegufy approved these changes

2024-05-15 13:36 UTC, merged