docs: add process picture for Registration Approval Process.md
eclipse-tractusx/portal-assets pull request #349
Opened 2024-06-24 04:16 UTC by jjeroch

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have added copyright and license headers, footers (for .md files) or files (for images)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-29 05:20 UTC, evegufy requested changes
the of the pic

2024-07-29 05:20 UTC, evegufy commented on docs/developer/01. Registration/04. Registration Approval/03. Registration Approval Process.md
> +
the size of the picture is 25kb and the quality is accordingly:
<img width="840" alt="image" src="https://github.com/user-attachments/assets/d6f0091c-2970-4a55-88ca-ffb405b36c18"
could you please provide a picture with better quality?

2024-07-30 06:35 UTC, jjeroch commented on docs/developer/01. Registration/04. Registration Approval/03. Registration Approval Process.md
> +
Done

2024-07-30 06:43 UTC, evegufy approved these changes

2024-07-30 06:43 UTC, merged