Offer Subscription documentation added
eclipse-tractusx/portal-assets pull request #38
Opened 2023-06-12 08:06 UTC by jjeroch

## Description

- added app subscription activation image
- create Service Subscription Activation (Provider) md-file
- update file names
- updated description of 01. Service Subscription.md
- created 02. Service Subscription Activation (Provider).md
- created 02. App Subscription Activation (Provider).md
- created 01.App Subscription Request Management.md
- updated 02. App Subscription Activation (Provider).md
- created 01. Subscription Flow.md
- updated hyperlinks and file intro
- updated 01.App Subscription Request Management.md
- updated 03. Subscription Overview (App Provider).md
- app release process files updated and restructured
- rename 01. Intro.md to index.md
- updated app & service release index.md
- offer autosetup documentation enhanced by new endpoint with process woorker

## Why

New feature development as well as feature enhancement in backend and frontend code

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-16 11:12 UTC, evegufy commented on docs/04. App(s)/02. App Release Process/02. App Detail Page.md
> +add sume details to the function
Could you please adjust this sentence?

2023-06-16 11:12 UTC, evegufy commented on docs/04. App(s)/02. App Release Process/02. App Detail Page.md
> +add sume details to the function
Could you please adjust this sentence?

2023-06-16 11:13 UTC, evegufy requested changes

2023-06-20 06:41 UTC, jjeroch commented on docs/04. App(s)/02. App Release Process/02. App Detail Page.md
> +add sume details to the function
done

2023-06-20 06:41 UTC, jjeroch commented on docs/04. App(s)/02. App Release Process/02. App Detail Page.md
> +add sume details to the function
done

2023-06-20 06:44 UTC, evegufy approved these changes

2023-06-20 06:45 UTC, merged