docs: adjust process worker documentation
eclipse-tractusx/portal-assets pull request #383
Opened 2024-08-09 08:18 UTC by Phil91

## Description

adjust process worker documentation

## Why

to be able to get a better understanding of the processes 

## Issue

Refs: #351

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-09 17:30 UTC, evegufy requested changes

2024-08-09 17:30 UTC, evegufy commented on docs/developer/09. Process Workers/01. application_checklist.md
>  The process worker communicates with the dim middle layer to create the wallet, or if disabled with the miw to create the wallet. It further more communicates with the bpdm, clearinghouse, the sd fac
could you please uppercase DIM in all place and explain what the abbreviation means once in the this file and also once in the dim_user_creation.md

2024-08-12 06:58 UTC, Phil91 commented on docs/developer/09. Process Workers/01. application_checklist.md
>  The process worker communicates with the dim middle layer to create the wallet, or if disabled with the miw to create the wallet. It further more communicates with the bpdm, clearinghouse, the sd fac
I've adjusted the pronunciation and added the explanation for the abbreviation.

2024-08-12 07:14 UTC, MaximilianHauer approved these changes

2024-08-14 06:25 UTC, evegufy approved these changes

2024-08-14 06:29 UTC, merged