docs: Create Toggle documentation for SD Factory skip
eclipse-tractusx/portal-assets pull request #396
Opened 2024-09-04 13:45 UTC by MaximilianHauer

## Description

Documentation regarding feature 
* https://github.com/eclipse-tractusx/sig-release/issues/796 

## Why

Documentation helps to understand the process.

## Issue

* https://github.com/eclipse-tractusx/sig-release/issues/796

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [X] I have added copyright and license headers, footers (for .md files) or files (for images)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2024-09-05 05:43 UTC, Phil91 requested changes

2024-09-05 05:43 UTC, Phil91 commented on docs/developer/01. Registration/04. Registration Approval/Toogle.md
> +```mermaid
We should align the diagrams with the ones in use-case-diagrams

2024-09-11 07:52 UTC, Phil91 approved these changes

2024-09-11 15:55 UTC, evegufy approved these changes

2024-09-11 15:56 UTC, merged