docs: organise as TRG folder structure
eclipse-tractusx/portal-assets pull request #428
Opened 2024-11-18 12:20 UTC by oyo

## Description

Organise docs according to TRG folder structure

## Why

Docs weren't structured as TRG 1 suggest.

## Issue

#400

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

2024-11-19 10:00 UTC, evegufy requested changes
could you please also add a docs/README.md file describing of what the documentation is made up on a high level? [example](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/tree/main/docs)

2024-11-19 10:00 UTC, evegufy commented on docs/api/README.md
> +Go to the [API Hub](https://eclipse-tractusx.github.io/api-hub/)
```suggestion
Please refer to the `docs/api` directory of the [portal-backend repository](https://github.com/eclipse-tractusx/portal-backend) or the [API Hub](https://eclipse-tractusx.github.io/api-hub/portal-backend) for the respective version you are interested in.
```

2024-11-21 13:39 UTC, evegufy requested changes

2024-11-21 13:39 UTC, evegufy commented on docs/admin/README.md
> +- [DB Views and Details](./DB+Views+and+Details/)
could you please fix all places where you use such `+` encodings, they don't work and result in 404 errors
```suggestion
- [DB Views and Details](./DB%20Views%20and%20Details/)
```

2024-11-21 14:07 UTC, oyo commented on docs/admin/README.md
> +- [DB Views and Details](./DB+Views+and+Details/)
done

2024-11-21 14:24 UTC, evegufy approved these changes

2024-11-21 14:25 UTC, merged