chore: extend Version Upgrade
eclipse-tractusx/portal-assets pull request #46
Opened 2023-06-16 09:34 UTC by Phil91

## Description

add description for the company credential detail database changes

## Why

To have the latest changes visible in the Version Upgrade

## Issue

N/A - Jira Ticket: CPLP-2853

## Corresponding Backend PR

[#84](https://github.com/eclipse-tractusx/portal-backend/pull/84)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-24 21:23 UTC, jjeroch requested changes

2023-07-24 21:23 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +
@Phil91 I suggest we add the following picture
![SSI Release 1 6 0 Introduction](https://github.com/catenax-ng/tx-portal-assets/assets/94133633/b123f468-aa04-4e1b-877e-88bbf172b1ab)

can you please validate it?

2023-07-24 21:23 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.company_ssi_details
@Phil91 I think we missed company_ssi_details_status - could you please check once

2023-07-24 21:26 UTC, jjeroch commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +
and likely the following as well
<img width="689" alt="image" src="https://github.com/eclipse-tractusx/portal-assets/assets/94133633/db1c9a14-1d58-41a1-905a-d13597791b1e">

2023-08-02 13:24 UTC, Phil91 commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +
on the first picture the table 'verified_credential_type_assigned_external_types' is missing. thats the linkage between 'verified_credential_types' and 'verified_credential_external_types'.

Where should i include the pictures in the folder structure?

2023-08-02 13:24 UTC, Phil91 commented on developer/Technical Documentation/Version Upgrade/portal-upgrade-details.md
> +* NEW: portal.company_ssi_details
added the missing items

2023-08-22 04:48 UTC, jjeroch approved these changes

2023-08-22 07:45 UTC, merged